#!/usr/bin/env python3
"""Installs OpenCode VTuber plugin bridge in ~/.config/opencode/plugins."""

from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
OPENCODE_PLUGINS_DIR = Path.home() / ".config" / "opencode" / "plugins"
BRIDGE_PATH = OPENCODE_PLUGINS_DIR / "opencode-vtuber-plugin.js"


def bridge_content() -> str:
    plugin_file = (PLUGIN_DIR / "plugin.js").as_posix()
    return (
        "// Auto-generated by opencode-vtuber-plugin/install.py\n"
        f'import {{ OpenCodeVtuberPlugin }} from "{plugin_file}";\n'
        "export { OpenCodeVtuberPlugin };\n"
        "export default OpenCodeVtuberPlugin;\n"
    )


def install() -> None:
    OPENCODE_PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    BRIDGE_PATH.write_text(bridge_content(), encoding="utf-8")
    print(f"Installed bridge plugin: {BRIDGE_PATH}")
    print("Restart OpenCode to load the plugin.")


def uninstall() -> None:
    if BRIDGE_PATH.exists():
        BRIDGE_PATH.unlink()
        print(f"Removed bridge plugin: {BRIDGE_PATH}")
    else:
        print("No bridge plugin found.")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--uninstall":
        uninstall()
    else:
        install()
